#!/usr/bin/env python3
"""
Apply :global() wrapping to dynamic CSS selectors in all converted Svelte modules.
Run this whenever selectors_to_wrap grows and existing files need updating.
"""

import re
import os
import glob

SELECTORS_TO_WRAP = [
    # ── Core shared ──────────────────────────────────────────────────────
    ".frame-strip",
    ".frame-cell",
    ".film-frame",
    ".film-frame.active",
    ".film-frame canvas",
    ".film-frame-num",
    ".hero-deco-col",
    ".hero-dot",
    ".preset-btn",
    ".preset-btn.active",
    ".preset-btn:hover",
    "h3",
    "code",
    "input[type='range']",
    "input[type='range']::-webkit-slider-thumb",
    ".btn",
    ".btn:hover",
    ".btn.active",
    ".btn.coral.active",
    ".btn.mint.active",
    ".btn.off",
    ".btn.off:hover",
    ".btn-row",
    ".spacing-chart-wrap",
    ".spacing-row",
    ".spacing-row-label",
    ".spacing-track",
    ".spacing-dot",
    ".weight-grid",
    ".weight-panel",
    ".weight-panel-title",
    ".weight-panel-preview",
    ".weight-panel:hover",
    ".weight-panel.active",
    ".lp-grid",
    ".lp-card",
    ".lp-card:hover",
    ".lp-card-icon",
    ".lp-card-label",
    ".pairing-grid",
    ".pairing-item",
    ".pairing-preview",
    ".pairing-label",
    ".pairing-info",
    ".pairing-score",
    ".pairing-item:hover",
    ".pairing-item.selected",
    ".contrast-pair",
    ".c-sample",
    ".contrast-ratio",
    ".pass-badge",
    ".fail-badge",
    ".demo-badge",
    ".demo-badge.interactive",
    ".demo-badge.challenge",
    ".seg-track",
    ".seg-marker",
    ".seg-label",
    ".seg-marker.key",
    ".seg-marker.mid",
    ".seg-track-label",
    ".buffer-cell",
    ".buffer-cell.X",
    ".buffer-cell.Y",
    ".buffer-cell.R",
    ".buffer-cell.G",
    ".buffer-cell.B",
    ".state-val",
    ".state-val.none",
    ".state-val.bound",
    ".log-line",
    ".log-line.bind",
    ".log-line.draw",
    ".log-line.gpu",
    ".log-line.info",
    ".question",
    ".lang-tag",
    ".cc-item",
    ".cc-item.bad",
    ".cc-item.good",
    ".debug-option",
    ".debug-option:hover",
    ".debug-option.correct",
    ".debug-option.wrong",
    ".debug-option.disabled",
    ".tl-layer-name-row",
    ".tl-layer-name-row:hover",
    ".tl-layer-name-row.selected",
    ".tl-layer-swatch",
    ".tl-layer-label",
    ".tl-layer-name-row.selected .tl-layer-label",
    ".tl-layer-eye",
    ".tl-layer-eye:hover",
    ".tl-ruler-tick",
    ".tl-ruler-num",
    ".tl-ruler-line",
    ".tl-ruler-line.major",
    ".tl-track-row",
    ".tl-track-bg",
    ".tl-keyframe",
    ".tl-keyframe:hover",
    ".tl-tween-bar",
    ".tl-tween-bar.hold",
    ".ls-layer",
    ".ls-layer:hover",
    ".ls-layer.selected",
    ".ls-layer.dragging",
    ".ls-layer-swatch",
    ".ls-layer-label",
    ".ls-drag-handle",
    ".curve-handle",
    ".curve-handle:hover",
    ".curve-handle.selected",
    ".rig-joint",
    ".rig-joint:hover",
    ".rig-joint.selected",
    ".bone-segment",
    ".ik-effector",
    ".ik-effector.dragging",
    ".skin-region",
    ".skin-region:hover",
    ".render-output",
    ".render-pixel",
    ".px-row",
    ".fs-item",
    ".fs-item-name",
    ".fs-item-size",
    ".fs-item-type",
    ".fs-folder",
    ".fs-file",
    ".walk-cycle-frame",
    ".walk-landmark",
    ".walk-path",
    ".highlight-box",
    ".highlight-label",
    ".clutter-item",
    ".ba-region",
    ".ba-region:hover",
    ".ba-region.selected",
    ".flow-node",
    ".flow-node:hover",
    ".flow-node.active",
    ".flow-edge",
    ".fk-bone",
    ".fk-bone.selected",
    # ── Two-col / callouts ─────────────────────────────────────────────
    ".two-col",
    ".callout.warn",
    ".callout.warn .callout-label",
    ".callout.violet",
    ".callout.violet .callout-label",
    ".callout.gold",
    ".callout.gold .callout-label",
    ".callout.green",
    ".callout.green .callout-label",
    ".callout.blue",
    ".callout.blue .callout-label",
    ".callout.orange",
    ".callout.orange .callout-label",
    ".callout.cyan",
    ".callout.cyan .callout-label",
    ".callout.amber",
    ".callout.amber .callout-label",
    ".callout.mint",
    ".callout.mint .callout-label",
    # ── GD Module02 ───────────────────────────────────────────────────
    ".ep-info strong",
    ".rot-score-label",
    ".rot-score-label span",
    # ── GD Module03 ───────────────────────────────────────────────────
    ".tf-anatomy",
    ".tf-tag.sage",
    ".tf-ann-line",
    ".audit-opt.correct",
    ".audit-opt.wrong",
    ".audit-opt.disabled",
    ".audit-feedback.ok",
    ".audit-feedback.bad",
    # ── GD Module04 ───────────────────────────────────────────────────
    ".h-swatch",
    ".h-swatch:hover",
    ".h-swatch-label",
    ".cc-badge",
    ".cc-badge.pass",
    ".cc-badge.fail",
    ".palette-opt.correct",
    ".palette-opt.wrong",
    ".palette-opt.disabled",
    ".palette-feedback.ok",
    ".palette-feedback.bad",
    # ── GD Module06 ───────────────────────────────────────────────────
    ".brand-layer",
    ".brand-layer .layer-title",
    ".brand-layer .layer-subtitle",
    ".brand-layer .layer-arrow",
    ".brand-layer.open .layer-arrow",
    ".layer-content",
    ".layer-content.open",
    ".layer-content ul",
    ".layer-content li",
    ".layer-content li::before",
    ".layer-content .layer-example",
    ".concept-score-row",
    ".concept-score-label",
    ".concept-score-bar-bg",
    ".concept-score-bar",
    ".concept-score-val",
    ".sgp-logo-area",
    ".sgp-logo-mark",
    ".sgp-brand-name",
    ".sgp-tagline",
    ".sgp-palette-row",
    ".sgp-swatch",
    ".sgp-type-row",
    ".sgp-heading",
    ".sgp-body-text",
    ".sgp-thumb",
    ".sgp-thumb-canvas",
    ".sgp-label",
    ".cc-touchpoint",
    ".cc-tp-label",
    ".cc-tp-canvas",
    ".cc-verdict-item",
    ".cc-verdict-icon",
    ".critique-specimen",
    ".critique-specimen-canvas",
    ".critique-specimen-label",
    ".critique-q",
    ".critique-opts",
    ".critique-opt",
    ".critique-opt:hover",
    ".critique-opt.correct",
    ".critique-opt.wrong",
    ".critique-opt.disabled",
    ".critique-feedback",
    ".critique-feedback.ok",
    ".critique-feedback.bad",
    # ── GD Module07 ───────────────────────────────────────────────────
    ".slider-row label",
    ".assess-q",
    ".assess-q-header",
    ".assess-q-body",
    ".assess-canvas-wrap",
    ".assess-canvas-wrap canvas",
    ".assess-q-text",
    ".assess-opts",
    ".assess-opt",
    ".assess-opt:hover",
    ".assess-opt.correct",
    ".assess-opt.wrong",
    ".assess-opt.disabled",
    ".assess-feedback",
    ".compare-item.selected",
    # ── GD Module08/09 ────────────────────────────────────────────────
    ".analogy-card",
    ".analogy-card:hover",
    ".analogy-card.selected",
    ".analogy-card canvas",
    ".analogy-card-label",
    ".seq-stage",
    ".seq-stage:last-child",
    ".seq-stage:hover",
    ".seq-stage.active",
    ".seq-stage:hover + .seq-stage",
    ".seq-stage.active + .seq-stage",
    ".seq-stage-num",
    ".seq-stage-label",
    ".reduction-step-btn",
    ".reduction-step-btn:hover",
    ".reduction-step-btn.active",
    ".reduction-step-btn .step-num",
    ".sb-panel",
    ".sb-panel.selected",
    ".sb-panel canvas",
    ".sb-panel-footer",
    ".sb-panel-num",
    ".sb-strip-item",
    ".sb-strip-item canvas",
    ".sb-strip-label",
    ".assess-question",
    ".assess-q-hdr",
    ".assess-canvas-row",
    ".assess-canvas-row canvas",
    ".assess-fb",
    ".assess-fb.ok",
    ".assess-fb.bad",
    # ── GD Module10 ───────────────────────────────────────────────────
    ".checklist-module",
    ".checklist-module-header",
    ".checklist-module-title",
    ".checklist-module-progress",
    ".checklist-module-bar",
    ".checklist-module-bar-fill",
    ".checklist-items",
    ".checklist-item",
    ".checklist-item:last-child",
    ".checklist-item:hover",
    ".checklist-item.done .ci-box",
    ".checklist-item.done .ci-check",
    ".checklist-item.done .ci-text",
    ".ci-box",
    ".ci-check",
    ".ci-text",
    ".ci-tag",
    ".sg-logo-variant",
    ".sg-logo-variant-label",
    ".sg-dont",
    ".sg-dont::before",
    ".sg-do",
    ".sg-do::before",
    ".sg-color-chip",
    ".sg-color-chip-swatch",
    ".sg-color-chip-info",
    ".sg-color-chip-name",
    ".sg-color-chip-role",
    ".sg-color-chip-val",
    ".sg-type-row",
    ".sg-type-row:last-child",
    ".sg-type-spec",
    ".sg-type-tag",
    ".sg-icon-cell",
    ".sg-icon-cell canvas",
    ".sg-icon-cell-label",
    ".sg-voice-pair",
    ".sg-voice-do",
    ".sg-voice-dont",
    ".sg-voice-label",
    ".sg-voice-text",
    ".export-card",
    ".export-card-header",
    ".export-card-fmt",
    ".export-card-type",
    ".export-card-body",
    ".export-card-uses",
    ".export-use-item",
    ".export-use-dot",
    ".export-card-warn",
    ".audit-q-item",
    ".audit-q-header",
    ".audit-q-header.answered-yes",
    ".audit-q-header.answered-no",
    ".audit-q-body",
    ".audit-q-cat",
    ".audit-q-btns",
    ".audit-q-btn",
    ".audit-q-btn.yes",
    ".audit-q-btn.no",
    ".audit-result.visible",
    ".audit-area-item",
    # ── VS Module08 ───────────────────────────────────────────────────
    ".cut-type-cell",
    ".cut-type-cell:hover",
    ".cut-type-cell.selected",
    ".cut-type-icon",
    ".cut-type-name",
    ".cut-type-cell.selected .cut-type-name",
    ".cut-detail strong",
    ".rs-word",
    ".rs-word:hover",
    ".rs-word.flagged-redundant",
    ".rs-word.flagged-filler",
    ".rs-word.flagged-keeper",
    ".rs-mode-btn.on-redundant",
    ".rs-mode-btn.on-filler",
    ".rs-mode-btn.on-keeper",
    ".tc-timeline",
    ".tc-label",
    ".tc-clips",
    ".tc-clip",
    ".tc-cut-line",
    ".tc-playhead",
    ".tc-metric",
    ".tc-metric-val",
    ".tc-metric-lbl",
    ".eda-segment",
    ".eda-segment:hover",
    ".eda-segment-label",
    ".eda-cut-marker",
    ".eda-annotation",
    ".momentum-clip-chip",
    ".momentum-clip-chip.selected",
    ".momentum-clip-chip:not(.selected)",
    # ── VS Module09/10 ────────────────────────────────────────────────
    ".csb-swatch-row",
    ".csb-swatch",
    ".csb-swatch.selected",
    ".csb-swatch-label",
    ".csb-role-row",
    ".csb-role-cell",
    ".csb-role-cell.active",
    ".color-picker-wrap",
    ".color-picker-label",
    ".color-picker-swatch",
    ".color-picker-swatch:hover",
    ".color-picker-hex",
    ".color-picker-hex:focus",
    ".color-harmony-tag",
    ".type-role-card",
    ".type-role-card:hover",
    ".type-role-card.selected",
    ".type-role-name",
    ".type-role-card.selected .type-role-name",
    ".type-preview",
    ".font-option",
    ".font-option:hover",
    ".font-option.selected",
    ".font-option-preview",
    ".font-option-meta",
    ".font-option-name",
    ".cc-frame-pair",
    ".cc-frame",
    ".cc-frame:hover",
    ".cc-frame canvas",
    ".cc-frame-label",
    ".pipeline-stage",
    ".pipeline-stage:hover",
    ".pipeline-stage.active",
    ".pipeline-stage.done",
    ".ps-header",
    ".ps-num",
    ".ps-title",
    ".ps-badge",
    ".ps-body",
    ".ps-tasks",
    ".ps-task",
    ".ps-task:last-child",
    ".ps-task-check",
    ".ps-task-check.checked",
    ".ps-task-text",
    ".ps-task-text.done",
    ".ps-module-ref",
    ".pipeline-stage.active .ps-num",
    ".pipeline-stage.done .ps-num",
    ".pipeline-stage.active .ps-title",
    ".pipeline-stage.active .ps-body",
    ".checklist-group",
    ".checklist-group-label",
    ".check-box",
    ".capstone-badge",
    ".course-complete",
    ".cc-title",
    ".cc-sub",
    # ── Game Dev Module11/12 ──────────────────────────────────────────
    ".slider-row input[type='range']",
    ".slider-row input[type='range']::-webkit-slider-thumb",
    ".slider-val",
    ".info-panel",
    ".info-row",
    ".info-key",
    ".info-val",
    ".polish-item",
    ".polish-item:last-child",
    ".polish-check",
    ".polish-check.done",
    ".polish-label",
    ".polish-label.done",
    ".mat4",
    ".m4c",
    ".m4c.hi",
    ".mat-label",
    ".pipeline3d",
    ".p3d-stage",
    ".p3d-stage:last-child",
    ".p3d-stage:hover",
    ".p3d-stage.active",
    ".p3d-name",
    ".p3d-sub",
    ".p3d-detail",
    ".depth-strip",
    ".depth-cell",
    ".complete-banner",
    ".complete-title",
    ".complete-sub",
    ".module-grid",
    ".mod-chip",
    ".mod-chip.done",
    ".demo-badge.i",
    ".demo-badge.a",
    ".demo-badge.g",
    ".btn.g:hover",
    ".btn.g.active",
    ".btn.o:hover",
    ".btn.o.active",
]


def apply_globals(css: str, selectors: list[str]) -> str:
    for sel in selectors:
        escaped = re.escape(sel)
        # Only wrap if not already :global(...)
        css = re.sub(
            rf"(?<!:global\()(?<![a-zA-Z0-9_\-]){escaped}(?P<suffix>[\s{{,>+~])",
            rf":global({sel})\g<suffix>",
            css,
        )
    return css


def fix_svelte_file(path: str, selectors: list[str]) -> bool:
    with open(path, "r", encoding="utf-8") as f:
        content = f.read()

    style_match = re.search(r"<style>(.*?)</style>", content, re.DOTALL)
    if not style_match:
        return False

    original_css = style_match.group(1)
    new_css = apply_globals(original_css, selectors)

    if new_css == original_css:
        return False

    new_content = (
        content[: style_match.start(1)] + new_css + content[style_match.end(1) :]
    )
    with open(path, "w", encoding="utf-8") as f:
        f.write(new_content)
    return True


if __name__ == "__main__":
    root = os.path.join(os.path.dirname(__file__), "..", "src", "lib", "modules")
    patterns = [
        os.path.join(root, "graphic-design", "*.svelte"),
        os.path.join(root, "visual-storytelling", "*.svelte"),
        os.path.join(root, "game-dev", "*.svelte"),
        os.path.join(root, "animation", "*.svelte"),
    ]
    changed = 0
    for pattern in patterns:
        for path in sorted(glob.glob(pattern)):
            if fix_svelte_file(path, SELECTORS_TO_WRAP):
                print(f"  patched  {os.path.relpath(path)}")
                changed += 1
            else:
                print(f"  no-op    {os.path.relpath(path)}")
    print(f"\nDone — {changed} file(s) updated.")
